project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "talk/**/*.qmd"
    - "project/**/*.qmd"
    - "about/index.*md"
  post-render:
    # - "rsync --recursive --prune-empty-dirs --copy-links --safe-links static/. _site/"
    - "cp -r static/. _site/"

website:
  title: "FIMS"
  site-url: https://www.garrickadenbuie.com
  repo-url: https://github.com/gadenbuie/garrickadenbuie-com
  repo-actions:
    - source
    - edit
    - issue
  open-graph: true
  navbar:
    title: FIMS
    background: light
    right:
      - text: blog
        href: blog/index.qmd
      - text: projects
        href: project/index.qmd
      - text: talks
        href: talk/index.qmd
      - text: about
        href: about/index.qmd
      - icon: github
        href: https://github.com/NOAA-FIMS
  page-footer:
    border: false
    background: light
    left: >-
       © {{< now year >}} FIMS
    right: >-
      <a class="link-dark me-1" Made with 💙</a>
    center: >-
      <a class="link-dark" href="https://github.com/NOAA-FIMS" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark" href="https://noaa-fims.r-universe.dev" title="r-project" target="_blank" rel="noopener">{{< fa brands r-project >}}</a>

format:
  html:
    theme:
      light:
        - zephyr
        - _assets/styles-elm-light.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
      dark:
        - _assets/zephyr-dark.scss
        - _assets/styles-elm-dark.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
    css:
      - _assets/panelset-extras.css
    highlight-style:
      light: _assets/syntax-elm-light.theme
      dark: _assets/syntax-elm-dark.theme
    code-block-bg: false
    include-in-header:
      text: <script src="https://cdn.counter.dev/script.js" data-id="10454114-dc3f-4c23-a4da-87e7f2c7c58d" data-utcoffset="-4"></script>

execute:
  freeze: auto

