project:
  type: website
  render:
    - "*.qmd"
    - "sites/*.qmd"
    - "about/index.*md"
  # post-render:
  #   - "cp -r static/. _site/"

website:
  title: "FIMS"
  site-url: https://noaa-fims.github.io/
  repo-url: https://github.com/NOAA-FIMS/noaa-fims.github.io
  repo-actions:
    - source
    - edit
    - issue
  open-graph: true
  navbar:
    title: FIMS
    background: light
    right:
      - text: sites
        href: sites/sites_index.qmd
      - text: about
        href: about/index.qmd
      - icon: github
        href: https://github.com/NOAA-FIMS
  page-footer:
    border: false
    background: light
    left: >-
      <span id="copyright-year"></span> FIMS
    right: >-
      <a class="link-dark" href="https://github.com/NOAA-FIMS" title="github" target="_blank" rel="noopener"><i class="fab fa-github"></i></a>
      <a class="link-dark" href="https://noaa-fims.r-universe.dev" title="r-project" target="_blank" rel="noopener"><i class="fab fa-r-project"></i></a>

format:
  html:
    header-includes: |
      <script>
        window.addEventListener('DOMContentLoaded', function() {
          var year = new Date().getFullYear();
          var el = document.getElementById('copyright-year');
          if (el) el.textContent = '© ' + year;
        });
      </script>
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    theme:
      light:
        - zephyr
        - _assets/styles-elm-light.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
      dark:
        - _assets/zephyr-dark.scss
        - _assets/styles-elm-dark.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
    css:
      - _assets/panelset-extras.css
    highlight-style:
      light: _assets/syntax-elm-light.theme
      dark: _assets/syntax-elm-dark.theme
    code-block-bg: false
    # If we want analystics we can add them through this code and creating a counter.dev dashboard
    # include-in-header:
    #   text: <script src="https://cdn.counter.dev/script.js" data-id="10454114-dc3f-4c23-a4da-87e7f2c7c58d" data-utcoffset="-4"></script>

execute:
  freeze: auto

