project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "sites/*.qmd"
    - "about/*qmd"
  resources:
    - images/
    - assets/
  post-render:
    - "cp -r _static/. docs/"

website:
  title: "FIMS"
  site-url: https://e-perl-noaa.github.io/fims-website-test
  repo-url: https://github.com/e-perl-noaa/fims-website-test
  repo-actions:
    - source
    - edit
    - issue
  open-graph: true
  navbar:
    title: FIMS
    background: light
    right:
      - text: home
        href: index.qmd
      - text: about
        menu:
          - text: about
            href: about/index.qmd
          - text: fims team
            href: about/contributors.qmd
          - text: faq
            href: about/faq.qmd
      - text: fims weekly
        href: fims-weekly/index.qmd
      - text: sites
        href: sites/sites_index.qmd
      - text: changelog
        href: FIMS_CHANGELOG.qmd
      - icon: github
        href: https://github.com/NOAA-FIMS
  page-footer:
    border: false
    background: light
    left: >-
      <span id="copyright-year"></span> FIMS
    right: >-
      <a class="link-dark" href="https://github.com/NOAA-FIMS" title="github" target="_blank" rel="noopener"><i class="fab fa-github"></i></a>
      <a class="link-dark" href="https://noaa-fims.r-universe.dev" title="r-project" target="_blank" rel="noopener"><i class="fab fa-r-project"></i></a>

format:
  html:
    body-width: 100%
    anchor-sections: true
    include-after-body: assets/open-in-new-tab.html
    header-includes: |
      <script>
        window.addEventListener('DOMContentLoaded', function() {
          var year = new Date().getFullYear();
          var el = document.getElementById('copyright-year');
          if (el) el.textContent = '© ' + year;
        });
      </script>
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    theme:
      light:
        - zephyr
        - assets/styles-elm-light.scss
        - assets/styles-elm-base.scss
        - assets/colors.scss
      dark:
        - assets/zephyr-dark.scss
        - assets/styles-elm-dark.scss
        - assets/styles-elm-base.scss
        - assets/colors.scss
    css:
      - assets/panelset-extras.css
    highlight-style:
      light: assets/syntax-elm-light.theme
      dark: assets/syntax-elm-dark.theme
    code-block-bg: false
    # If we want analystics we can add them through this code and creating a counter.dev dashboard
    # include-in-header:
    #   text: <script src="https://cdn.counter.dev/script.js" data-id="10454114-dc3f-4c23-a4da-87e7f2c7c58d" data-utcoffset="-4"></script>

execute:
  freeze: auto

