name: Check for Broken Links

# This action will run whenever you push new code to your main branch
on:
  push:
    branches:
      - main
  # You can also run it on a schedule (e.g., every Monday at 1 AM)
  # schedule:
  #   - cron: '0 1 * * 1'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build Quarto Site
        run: quarto render

      # Step 3: Run the broken link checker
      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: .

      # Step 4: Add a summary report to the workflow run
      # This step makes the output of the link checker easy to read
      - name: Fail if there are broken links
        if: steps.lychee.outputs.exit_code == 1
        run: |
          echo "## 🚨 Broken Links Found" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.lychee.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
          exit 1